#Note: This script does not used build-wheels.sh nor the Makefile included in this repo (that's for local usage)

name: Build Wheels

on: [workflow_dispatch]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
           CIBW_ARCHS_LINUX: "x86_64"
           CIBW_ARCHS_MACOS: "x86_64"
           CIBW_BEFORE_ALL_LINUX: >
              if command -v apt-get; then
                apt-get -y git libicu-dev libxml2-dev libexttextcat-dev libxslt1-dev libbz2-dev zlib1g-dev autoconf automake autoconf-archive libtool autotools-dev gcc g++ make
              elif command -v yum; then
                yum install -y git libicu-devel libxml2-devel libxslt-devel libexttextcat zlib-devel bzip2-devel libtool autoconf-archive autoconf automake m4 wget
                #on CentOS 7 we also have libtar-devel libexttextcat-devel which will be installed by build-deps.sh, on 8 they are missing and will be installed from source or otherwise
              elif command -v apk; then
                apk add build-base git autoconf-archive autoconf automake libtool bzip2-dev icu-dev libxml2-dev libexttextcat-dev libtool rsync &&
                rsync -av --ignore-existing /usr/share/aclocal/*.m4 /usr/local/share/aclocal/
              fi &&
              ./build-deps.sh
           CIBW_BEFORE_ALL_MACOS: >
              brew tap fbkarsdorp/homebrew-lamachine &&
              brew install ucto
              find /usr/ -type f -name "*folia*" || true
              find /opt/ -type f -name "*folia*" || true
           CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64
           CIBW_SKIP: "*-win* *-manylinux_i686 pp*"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
